### ISSUE TITLE
JavaScript error, no results on results page

### ISSUE THREAD

**Issue by kevinschaul** [openelections/openelections.github.io#50]
I am seeing a JavaScript error on the [results page](http://openelections.net/results/) and no results are showing up. Looks like it is coming from results.js. I may do some digging to see if it's an easy fix.

Great work on this project!

![image](https://cloud.githubusercontent.com/assets/675639/10958356/2c3bb434-833b-11e5-93e2-8bfe618dba3a.png)

**Comment by dwillis** [comment]
I need to remove the link to /results/ - it's not supposed to work. What works is /results/#stateabbrev, such as http://openelections.net/results/#ms
